name: deployment

# deploy to digital ocean on push to main with tag release
on:
  push:
    branches:
      - main
    tags:
      - release

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo ${{ secrets.SSH_KEY }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy to Digital Ocean
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: |
  #           cd server/
  #           git pull origin main
  #           npm install
  #           npm run test
  #           npm run build
  #           pm2 restart all
