# echo on pushes to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: |
          echo {{secrets.SSH_HOST}}
          echo {{secrets.SSH_KEY}}
          echo {{secrets.SSH_USERNAME}}
          
