# echo on pushes to main
on:
  push:
    tags:
      - "release-*"

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: |
          echo {{secrets.SSH_HOST}}
