#echo on pushes with tags release-*
on:
  push:
    tags:
      - release-*
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: |
          echo {{secrets.SSH_HOST}}
